# Generated by Django 4.2 on 2023-04-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_author_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
